[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.1",
    "matplotlib>=3.10.3",
    "openpyxl>=3.1.5",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]
